In [1]:
import numpy as np

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand()

0.6149933151839352

In [9]:
np.random.rand(4)

array([0.09904639, 0.88868034, 0.09023607, 0.12458973])

In [10]:
np.random.rand(4,4)

array([[0.28293022, 0.43379891, 0.7318165 , 0.36000941],
       [0.4449177 , 0.50442022, 0.92691862, 0.04515357],
       [0.18397814, 0.15444378, 0.54489843, 0.71851422],
       [0.94367959, 0.31733723, 0.44501053, 0.22363489]])

In [17]:
np.random.randint(1,10,(5,5))

array([[4, 3, 5, 8, 8],
       [5, 7, 8, 3, 7],
       [4, 5, 5, 6, 4],
       [6, 6, 1, 5, 3],
       [4, 4, 2, 3, 9]])

In [18]:
arr = np.random.randint(1,10,(3,2))

In [19]:
arr.shape

(3, 2)

In [20]:
print(arr)

[[8 1]
 [3 5]
 [6 2]]


In [21]:
arr.reshape(1,6)

array([[8, 1, 3, 5, 6, 2]])

In [25]:
arr.reshape(2,3)

array([[8, 1, 3],
       [5, 6, 2]])

In [23]:
np.reshape(arr,(2,3),'C')

array([[8, 1, 3],
       [5, 6, 2]])

In [26]:
np.reshape(arr,(2,3),'f')

array([[8, 6, 5],
       [3, 1, 2]])

In [30]:
arr = np.random.randint(1,20,10)

In [31]:
matriz = arr.reshape(2,5)
print(matriz)

[[10  4  3 19  3]
 [12 11  5  1 19]]


In [33]:
arr.max()

19

In [35]:
"el valor maximo por fila"
matriz.max(1)

array([19, 19])

In [36]:
"el indice del valor maximo"
arr.argmax()

3

In [39]:
arr.min()

1

In [38]:
arr.argmin(0)

8

In [41]:
arr.sort()
print(arr)

[ 1  3  3  4  5 10 11 12 19 19]


In [44]:
"el valor que se encuentra a la mitad (si fuera 100 es el valor mas alto)"
np.percentile(arr,50)

7.5

In [43]:
np.median(arr)

7.5

In [45]:
"mediana (mitad de la distribucion)"
np.median(matriz,1)

array([ 3., 12.])

In [48]:
"desviacion estandar"
np.std(arr)

6.245798587850877

In [47]:
"varianza"
np.var(arr)

39.010000000000005

In [49]:
"mediana"
np.mean(arr)

8.7

In [51]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [56]:
"para que b tenga la misma dimension que a"
b=np.expand_dims(b,axis=0)

In [59]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [62]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [63]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [64]:
arr_copy = arr.copy()

In [65]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [66]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [69]:
"condiciones"
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [70]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[(arr>5)&(arr<9)]

array([6, 7, 8], dtype=int8)

In [73]:
arr[arr>5]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [76]:
"OPERACIONES"
lista = [1,2]
lista

[1, 2]

In [78]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [79]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [85]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [86]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [87]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [89]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz