In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]

In [31]:
"En jupyter Notebook no hay que poner print()"
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr=np.array(lista)

In [8]:
type(arr)

numpy.ndarray

In [9]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr[0] + arr[5]

7

In [12]:
matriz[0,2]

3

In [17]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [25]:
"tipo de datos"
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [19]:
arr


array([1., 2., 3., 4.])

In [21]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [22]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [23]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [28]:
"dimensiones"
scalar = np.array(42)
scalar
scalar.ndim "indica n° de dimensiones"

0

In [30]:
vector = np.array([1,2,3])
vector
vector.ndim

1

In [33]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz
matriz.ndim

2

In [40]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
tensor.ndim

3